/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assessor;

import assessor.ui.UserSettings;
import assessor.util.CurrencyRenderer;
import assessor.util.DateRenderer;
import assessor.util.NonEditableTableModel;
import assessor.util.KeyboardRefresh;
import assessor.util.ReportLoader;
import assessor.util.ReportLoader.LoadCallbacks;
import assessor.util.TableRightRenderer;
import assessor.util.TimeRenderer;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Toryang
 */
public class MainWindow extends javax.swing.JFrame {
    private UserSettings userSettings;
    
    private ReportLoader reportLoader;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        userSettings = new UserSettings("defaultPassword");
        postInitSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 5));
        jMainPanel = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        jNoLandHoldingPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jReportPanel = new javax.swing.JPanel();
        jReportScrollPane = new javax.swing.JScrollPane();
        jTableReports = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1800, 1000));

        btnRefresh.setText("Refresh");

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("NO LANDHOLDING");

        jButton1.setText("jButton1");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton2.setText("jButton2");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton3.setText("jButton3");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton4.setText("jButton4");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton5.setText("jButton5");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton6.setText("jButton6");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jNoLandHoldingPanelLayout = new javax.swing.GroupLayout(jNoLandHoldingPanel);
        jNoLandHoldingPanel.setLayout(jNoLandHoldingPanelLayout);
        jNoLandHoldingPanelLayout.setHorizontalGroup(
            jNoLandHoldingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNoLandHoldingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jNoLandHoldingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        jNoLandHoldingPanelLayout.setVerticalGroup(
            jNoLandHoldingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNoLandHoldingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addComponent(jNoLandHoldingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNoLandHoldingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addContainerGap())
        );

        jTableReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jReportScrollPane.setViewportView(jTableReports);

        javax.swing.GroupLayout jReportPanelLayout = new javax.swing.GroupLayout(jReportPanel);
        jReportPanel.setLayout(jReportPanelLayout);
        jReportPanelLayout.setHorizontalGroup(
            jReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jReportScrollPane)
                .addContainerGap())
        );
        jReportPanelLayout.setVerticalGroup(
            jReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jReportScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jReportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    private void postInitSetup() {
        
	setTitle("Assessor Certification");
        // Configure table with fresh model immediately
        NonEditableTableModel cleanModel = new NonEditableTableModel();
        jTableReports.setModel(cleanModel);
        
        // Initialize loader with callback for UI updates
        reportLoader = new ReportLoader(cleanModel, new LoadCallbacks() {
            @Override
            public void onLoadStart() {
                btnRefresh.setEnabled(false);
                cleanModel.setRowCount(0);
                cleanModel.addRow(new Object[]{"Loading reports..."});
            }

            @Override
            public void onLoadComplete() {
                btnRefresh.setEnabled(true);
                configureColumnRenderers(); // ADD THIS LINE
            }

            @Override
            public void onLoadError(String message) {
                cleanModel.setRowCount(0);
                cleanModel.addRow(new Object[]{"Error: " + message});
                btnRefresh.setEnabled(true);
            }
        });
    
        // Setup refresh button
        btnRefresh.addActionListener(e -> reportLoader.loadData());
        
        new KeyboardRefresh(reportLoader, this);
                
        // Initial load
        reportLoader.loadData();
        
        setupUserButton();
    }
    
    private void setupUserButton() {
        JMenuBar menuBar = this.jMenuBar1;
        menuBar.add(Box.createHorizontalGlue());

        JButton userButton = new JButton();
        userButton.putClientProperty("JButton.buttonType", "toolBarButton");
        userButton.setFocusable(false);
        userButton.setToolTipText("User Settings");

        // Load SVG icon
        try {
            FlatSVGIcon svgIcon = new FlatSVGIcon("assessor/ui/icons/users.svg", 15, 15);
            userButton.setIcon(svgIcon);
        } catch(Exception e) {
            // Fallback to standard icon
            ImageIcon icon = new ImageIcon(getClass().getResource("/assessor/ui/icons/users.png"));
            userButton.setIcon(icon);
            userButton.setText("User");
        }

        userButton.addActionListener(e -> showPasswordDialog());
        menuBar.add(userButton);
    }
    
    private void showPasswordDialog() {
        JDialog dialog = new JDialog(this, "Change Password", true);
        dialog.setLayout(new BorderLayout());
        dialog.setResizable(false);

        // Header Panel
        JPanel headerPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JLabel headerLabel = new JLabel("Account Security");
        headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        headerLabel.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
        headerPanel.add(headerLabel);

        // Form Panel
        JPanel formPanel = new JPanel();
        formPanel.setLayout(new BoxLayout(formPanel, BoxLayout.Y_AXIS));
        formPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));

        InputField currentPassField = new InputField("Current Password", true);
        InputField newPassField = new InputField("New Password", true);
        newPassField.setStrengthMeter(true);
        InputField confirmPassField = new InputField("Confirm Password", true);

        formPanel.add(currentPassField);
        formPanel.add(Box.createVerticalStrut(10));
        formPanel.add(newPassField);
        formPanel.add(Box.createVerticalStrut(10));
        formPanel.add(confirmPassField);

        // Action Panel
        JPanel actionPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        actionPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 10, 10));

        JButton btnCancel = new JButton("Cancel");
        JButton btnSubmit = new JButton("Update Password");
        btnSubmit.setBackground(new Color(0, 120, 215));
        btnSubmit.setForeground(Color.WHITE);

        btnSubmit.addActionListener(e -> processPasswordChange(
            currentPassField.getPassword(),
            newPassField.getPassword(),
            confirmPassField.getPassword(),
            dialog
        ));

        btnCancel.addActionListener(e -> dialog.dispose());

        actionPanel.add(btnCancel);
        actionPanel.add(btnSubmit);

        dialog.add(headerPanel, BorderLayout.NORTH);
        dialog.add(formPanel, BorderLayout.CENTER);
        dialog.add(actionPanel, BorderLayout.SOUTH);

        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    // Custom Input Field Component
    class InputField extends JPanel {
        private JPasswordField passwordField;
        private JProgressBar strengthBar;

        public InputField(String label, boolean isPassword) {
            setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

            JLabel fieldLabel = new JLabel(label);
            fieldLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));

            if(isPassword) {
                passwordField = new JPasswordField(20);
            } else {
                passwordField = new JPasswordField(20);
                passwordField.setEchoChar((char)0);
            }

            passwordField.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200)),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
            ));

            add(fieldLabel);
            add(Box.createVerticalStrut(5));
            add(passwordField);
        }

        public void setStrengthMeter(boolean enabled) {
            if(enabled) {
                strengthBar = new JProgressBar(0, 4);
                strengthBar.setStringPainted(true);
                strengthBar.setString("Strength");
                strengthBar.setForeground(new Color(0, 180, 0));
                add(Box.createVerticalStrut(5));
                add(strengthBar);

                passwordField.getDocument().addDocumentListener(new DocumentListener() {
                    public void changedUpdate(DocumentEvent e) { update(); }
                    public void insertUpdate(DocumentEvent e) { update(); }
                    public void removeUpdate(DocumentEvent e) { update(); }

                    private void update() {
                        String pass = new String(passwordField.getPassword());
                        int strength = calculatePasswordStrength(pass);
                        strengthBar.setValue(strength);
                    }
                });
            }
        }

        private int calculatePasswordStrength(String pass) {
            int strength = 0;
            if(pass.length() >= 8) strength++;
            if(pass.matches(".*[A-Z].*")) strength++;
            if(pass.matches(".*\\d.*")) strength++;
            if(pass.matches(".*[^a-zA-Z0-9].*")) strength++;
            return strength;
        }

        public char[] getPassword() {
            return passwordField.getPassword();
        }
    }
    
        private void processPasswordChange(char[] currentPass, 
                                      char[] newPass, 
                                      char[] confirmPass, 
                                      JDialog dialog) {
        try {
            if (!userSettings.validateCurrentPassword(currentPass)) {
                JOptionPane.showMessageDialog(dialog,
                    "Invalid current password",
                    "Authentication Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            userSettings.validateNewPassword(newPass, confirmPass);
            userSettings.changePassword(newPass);

            JOptionPane.showMessageDialog(dialog,
                "Password updated successfully!\nPlease login again.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

            dialog.dispose();
        } catch(IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(dialog,
                ex.getMessage(),
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        } finally {
            Arrays.fill(currentPass, '\0');
            Arrays.fill(newPass, '\0');
            Arrays.fill(confirmPass, '\0');
        }
    }
    
    private void configureColumnRenderers() {
        DefaultTableModel model = (DefaultTableModel) jTableReports.getModel();
        
        for (int i = 0; i < model.getColumnCount(); i++) {
            TableColumn column = jTableReports.getColumnModel().getColumn(i);
            String colName = model.getColumnName(i).toLowerCase();
            switch (colName) {
                case "id":
                    column.setHeaderValue("ID");
                    column.setCellRenderer(new TableRightRenderer());
                    column.setPreferredWidth(50);
                    column.setMaxWidth(50);
                    column.setMinWidth(50);
                    break;
                case "certificationdate":
                    column.setHeaderValue("Certification Date");
                    column.setCellRenderer(new DateRenderer());
                    column.setPreferredWidth(120);  // mm-dd-yyyy format
                    column.setMaxWidth(120);
                    column.setMinWidth(120);
                    break;
                case "certificationtime":
                    column.setHeaderValue("Certification Time");
                    column.setCellRenderer(new TimeRenderer());
                    column.setPreferredWidth(100);  // hh:mm a format
                    column.setMaxWidth(120);
                    column.setMinWidth(120);
                    break;
                    
                case "parent2":
                    column.setHeaderValue("Parent");
                    column.setPreferredWidth(200);
                    column.setMaxWidth(200);
                    column.setMinWidth(200);
                    break;
                case "amount":
                    column.setCellRenderer(new CurrencyRenderer());
                    column.setPreferredWidth(80);  // Currency needs space for symbols/commas
                    column.setMaxWidth(80);
                    column.setMinWidth(80);
                    break;
                    
                default:
                    column.setPreferredWidth(200);
                    column.setMaxWidth(200);
                    column.setMinWidth(200);
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnRefresh;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jNoLandHoldingPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jReportPanel;
    private javax.swing.JScrollPane jReportScrollPane;
    private javax.swing.JTable jTableReports;
    // End of variables declaration//GEN-END:variables
}
